### ISSUE TITLE
XXX, BUG, TODO, FIXME, NOTE are not highlighted

### ISSUE THREAD

**Issue by yvvt0379** [christopherafbjur/vscode-theme-onedarker#1]
Atom One Darker:
![批注 2020-04-11 220107](https://user-images.githubusercontent.com/62426149/79045870-13ca5600-7c40-11ea-874f-1dc5c20f9ed0.png)
Default Dark+:
![批注 2020-04-11 220135](https://user-images.githubusercontent.com/62426149/79045893-38bec900-7c40-11ea-9ab0-86677bd870b4.png)
_(I added italic style to my `setting.json` file so comments look italic.)_

**Comment by christopherafbjur** [comment]
Thank you for reporting @BornForFever !
